/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package busattipichiugita;

/**
 *
 * @author Busatti Mattia e Pichiu Florin
 */
public class CaricaStudenteFrm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CaricaStudenteFrm.class.getName());

    private RecordStudente rs = new RecordStudente();
    private RecordRelazione rr = new RecordRelazione();

    /**
     * Creates new form CaricaDatiFrm
     */
    public CaricaStudenteFrm() {
        initComponents();
        aggiornaLista();
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE); //Per rimanere aperto senza che si chiuda tutto
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JTextField();
        txtCognome = new javax.swing.JTextField();
        txtClasse = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblCognome = new javax.swing.JLabel();
        lblClasse = new javax.swing.JLabel();
        btnAggiungi = new javax.swing.JButton();
        btnRimuovi = new javax.swing.JButton();
        lblGestioneStudenti = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtStudenti = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNome.setName("txtNome"); // NOI18N
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtCognome.setName("txtCognome"); // NOI18N
        txtCognome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCognomeActionPerformed(evt);
            }
        });

        txtClasse.setName("txtClasse"); // NOI18N
        txtClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClasseActionPerformed(evt);
            }
        });

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNome.setForeground(new java.awt.Color(0, 0, 204));
        lblNome.setText("NOME");

        lblCognome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCognome.setForeground(new java.awt.Color(0, 51, 204));
        lblCognome.setText("COGNOME");

        lblClasse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblClasse.setForeground(new java.awt.Color(0, 0, 204));
        lblClasse.setText("CLASSE");

        btnAggiungi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAggiungi.setForeground(new java.awt.Color(255, 0, 0));
        btnAggiungi.setText("AGGIUNGI");
        btnAggiungi.setName("btnAggiungi"); // NOI18N
        btnAggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggiungiActionPerformed(evt);
            }
        });

        btnRimuovi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRimuovi.setForeground(new java.awt.Color(255, 0, 0));
        btnRimuovi.setText("RIMUOVI");
        btnRimuovi.setName("btnRimuovi"); // NOI18N
        btnRimuovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRimuoviActionPerformed(evt);
            }
        });

        lblGestioneStudenti.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblGestioneStudenti.setForeground(new java.awt.Color(255, 0, 0));
        lblGestioneStudenti.setText("GESTIONE STUDENTI");

        lblID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblID.setForeground(new java.awt.Color(0, 0, 204));
        lblID.setText("ID");

        txtID.setName("txtClasse"); // NOI18N
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        txtStudenti.setColumns(20);
        txtStudenti.setRows(5);
        jScrollPane1.setViewportView(txtStudenti);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAggiungi)
                    .addComponent(btnRimuovi)
                    .addComponent(txtClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClasse)
                    .addComponent(txtCognome, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCognome)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblID)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(lblGestioneStudenti)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblGestioneStudenti)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblID)
                        .addGap(12, 12, 12)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCognome)
                        .addGap(6, 6, 6)
                        .addComponent(txtCognome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblClasse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAggiungi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRimuovi))
                    .addComponent(jScrollPane1))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCognomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCognomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCognomeActionPerformed

    private void txtClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClasseActionPerformed

    private void btnAggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggiungiActionPerformed
        String id = txtID.getText().trim();
        String nome = txtNome.getText().trim();
        String cognome = txtCognome.getText().trim();
        String classe = txtClasse.getText().trim();
        if (id.isEmpty() || nome.isEmpty() || cognome.isEmpty() || classe.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Compila tutti i campi.");
            return;
        }
        if (rs.cercaPerID(id) != -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "ID già esistente.");
            return;
        }
        rs.scriviRecord(new Studente(id, nome, cognome, classe));
        txtID.setText("");
        txtNome.setText("");
        txtCognome.setText("");
        txtClasse.setText("");
        aggiornaLista();
    }//GEN-LAST:event_btnAggiungiActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnRimuoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRimuoviActionPerformed
        String id = txtID.getText().trim();
        if (id.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Inserisci l'ID da rimuovere.");
            return;
        }
        if (rs.cercaPerID(id) == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Studente non trovato.");
            return;
        }
        for (String idGita : rr.getGiteStudente(id)) {
            rr.eliminaRecord(id, idGita);
        }
        rs.scriviRecordInPosizione(new Studente("00", "ELIMINATO", "ELIMINATO", "ELIM"), rs.cercaPerID(id));
        txtID.setText("");
        aggiornaLista();
    }//GEN-LAST:event_btnRimuoviActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CaricaStudenteFrm().setVisible(true));
    }

    private void aggiornaLista() {
        txtStudenti.setText("");
        txtStudenti.append(String.format("%-5s %-15s %-15s %-8s%n", "ID", "NOME", "COGNOME", "CLASSE"));
        txtStudenti.append("-".repeat(45) + "\n");
        for (Studente s : rs.leggiTutti()) {
            if (!s.getNome().equals("ELIMINATO")) {
                txtStudenti.append(String.format("%-5s %-15s %-15s %-8s%n",
                        s.getId(), s.getNome(), s.getCognome(), s.getClasse()));
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAggiungi;
    private javax.swing.JButton btnRimuovi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClasse;
    private javax.swing.JLabel lblCognome;
    private javax.swing.JLabel lblGestioneStudenti;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField txtClasse;
    private javax.swing.JTextField txtCognome;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextArea txtStudenti;
    // End of variables declaration//GEN-END:variables
}
